ping:
    type: presenter
    methods: [get]
    path: ping
    presenter: ping

"acme::product.export":
    type: presenter
    methods: [get]
    path: export-products
    presenter: "acme::product.export"
